### ISSUE TITLE
Do Fire bets normally pay out each time that they are hit, or only when the shooter concluded?

### ISSUE THREAD

**Issue by amortization** [skent259/crapssim#33]
So if the shooter has hit 4 points, does it pay out when the shooter has completed shooting, or does it pay out after the 4th point is made? I don't play fire often, but I thought that it payed out when x number of points are made so that is how it is in dev. However, at my local casino I asked them and it pays out when the shooter has concluded shooting, so I'm wondering if that varies, or if it should be changed?

**Comment by skent259** [comment]
After some reading of a detailed bet description (https://www.wsgc.wa.gov/sites/default/files/public/activities/GameRules/game-rules/57_fire-bet.pdf):

- Fire bet resolves only on a shooter seven out or when 6 points are made
- thus, if a shooter makes 4 points but keeps rolling, you don't see the payout until they seven out
- along the same vein, at most one payout should happen

**Comment by skent259** [comment]
Fixed this in dev branch with 1a4e812
